<a href="https://colab.research.google.com/github/kenanmorani/Audio_Signal_Processing_For_Music_Applications_idu/blob/main/simple_linear_regression_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
from sklearn import linear_model
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score

In [56]:
import matplotlib.pyplot as plt

In [39]:
dataset = pd.read_csv('/data/Extensographupdated.csv')

In [40]:
dataset.head()

Novamyl 1500MG  Lipopan FBG  ...  Develop.Time(min)  W.absorption
0              35            7  ...                3.5          61.0
1              75            7  ...                4.3          60.8
2              35            7  ...                4.8          61.1
3              75            7  ...                4.8          61.2
4              35            4  ...                4.5          61.1

[5 rows x 9 columns]

In [50]:
# The enzyms
x=dataset.iloc[:,0:3].values

In [51]:
x

array([[ 35,   7,  30],
       [ 75,   7,  30],
       [ 35,   7, 100],
       [ 75,   7, 100],
       [ 35,   4,  65],
       [ 75,   4,  65],
       [ 35,  10,  65],
       [ 75,  10,  65],
       [ 55,   4, 100],
       [ 55,  10,  30],
       [ 55,  10, 100],
       [ 55,   7,  65],
       [ 55,   7,  65]])

In [43]:
# The F.Q.Number
y=dataset.iloc[:,3:4].values

In [44]:
y

array([[65],
       [64],
       [67],
       [64],
       [63],
       [65],
       [67],
       [63],
       [61],
       [62],
       [64],
       [53],
       [56]])

In [45]:
# Reshaping array to cvonvert from 1D to 2D
# x=x.reshape(-1,1)

In [46]:
x

array([[ 35],
       [  7],
       [ 30],
       [ 75],
       [  7],
       [ 30],
       [ 35],
       [  7],
       [100],
       [ 75],
       [  7],
       [100],
       [ 35],
       [  4],
       [ 65],
       [ 75],
       [  4],
       [ 65],
       [ 35],
       [ 10],
       [ 65],
       [ 75],
       [ 10],
       [ 65],
       [ 55],
       [  4],
       [100],
       [ 55],
       [ 10],
       [ 30],
       [ 55],
       [ 10],
       [100],
       [ 55],
       [  7],
       [ 65],
       [ 55],
       [  7],
       [ 65]])

In [47]:
lin_reg=linear_model.LinearRegression()

In [52]:
# Fitting the model
lin_reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [54]:
# The mean square error
print("Coefficients:\n",lin_reg.coef_)
print("intercept:\n", lin_reg.intercept_)

Coefficients:
 [[-0.0375      0.23464912  0.01296992]]
intercept:
 [62.10322682]
